

# Exceptional handeling :  An exception is an event, which occurs during the execution of a program, that interrupt  the  normal flow of the program's instructions.

# the try block which is used to test a block of code for errors.
# the except block used to handle the errors.


 ##print('python developer')
 # ##a=int(input('Enter the first number: '))
 # ##b=int(input('Enter the second number: '))
 # ##try:
 # ##print(a/b)
 # ##except:
 # ##print('exception handeled')
 # ##print('java developer')



#print('Hiiii')
##a=[11,22,33,44,55]
##try:
##print(a[len(a)])
##except:
##print('list index out of range')
##print('Hello')




#print('Hiiii')
##a=[11,22,33,44,55]
##try:
##print(a[len(a)])
##except Exception as e:
##print(e)
##print('Hello')



#print('python developer')
##a=int(input('Enter the first number: '))
##b=int(input('Enter the second number: '))
##try:
##    print(a/b)
##except Exception as e:
##    print(e)
##print('java developer')


#print('python developer')
##
##
##try:
##    a=int(input('Enter the first number: '))
##    b=int(input('Enter the second number: '))
##    print(a/b)
##except Exception as e:
##    print('Value Error:',e)
##print('java developer')


#try:
    ##    print('Thane')
    # ##    print(2/0)
    # ##    print(int('demo'))
    # ##    print('Dadar')
    # ####except ZeroDivisionError as e:
    # ##    print(e)
    # ##    ##except Exception as e:
    # ##    print('exception handeled',e)


##try:
# ##    print('Thane')
# ##    print(2/0)
# ##    print(int('demo'))
# ##    print('Dadar')
# ##    ##except Exception as e:
# ##    print('exception handeled',e)
# ####except ZeroDivisionError as e:
# ##    print(e)    

##try:
# ##    print('Thane')
# ##    #print(2/0)
# ##    print(int('demo'))
# ##    print('Dadar')
# ##   ##except Exception as e:
# ##    print('exception handeled',e)
# ####except ZeroDivisionError as e:
# ##    print(e)####
# except ValueError as v:
# ##    print('value error',v)##    




